### ISSUE TITLE
how we can make infinite scroll

### ISSUE THREAD

**Issue by pankajninjasec** [dmt195/tiktok-flutter-plugin#1]
when i add more colors to the list it length of scrolling remains same I mean only 3 index values but I need infinite so what I can do
Thanks in advance

Regards
pankaj

**Comment by dmt195** [comment]
Thanks @pankajninjasec and sorry for the slow reply. 

The library has been written in a general way using `builder`, just like the `ListView.builder()` pattern. I found an example of how to write infinite scroll listviews [here](https://github.com/sharmadhiraj/flutter_infinite_listview/) and added this library to it to prove the principle. I copied my main file into a Gist [here](https://gist.github.com/dmt195/228434d84e8db2e2a6706f2e6c408b2d) for reference. See I've replaced `ListView.builder` with `TikTokStyleFullPageScroller` on line 79. I've tested it as working and I hope this helps.

I considered wrapping the library with some higher-level logic that would cover this use case but that makes it less generic.
