### ISSUE TITLE
Match widget size according to its container

### ISSUE THREAD

**Issue by ngallazzi** [dmt195/tiktok-flutter-plugin#2]
<img src="https://user-images.githubusercontent.com/7433125/116570226-64bff180-a90a-11eb-95b3-daf8a4059f63.gif" width="250">

Putting TikTokStyleFullPageScroller inside a container the scroller takes wrong size and height for itself, keeping full page size.

**Comment by dmt195** [comment]
Thanks for the issue and the pull request. I've merged your PR and fixed a related bug (identified when the container was centred). This should be published to pub.dev shortly. 🎉
